export const year = [
  { label: "1st", value: "1st" },
  { label: "2nd", value: "2nd" },
  { label: "3rd", value: "3rd" },
  { label: "4th", value: "4th" },
  { label: "5th", value: "5th" },
  { label: "Pass-out", value: "passout" },
] as const;

export const ministry = [
  { label: "General Team", value: "General Team" },
  { label: "Media", value: "Media" },
  { label: "Finance", value: "Finance" },
  { label: "Mobilization", value: "Mobilization" },
  { label: "Program", value: "Program" },
  { label: "Intercession", value: "Intercession" },
  { Label: "Resource Caring", value: "Resource Caring" },
  { Label: "Decoration", value: "Decoration" },
  { Label: "Liturgy", value: "Liturgy" },
  { Label: "Kitchen and Food", value: "Kitchen and Food" },
  { Label: "Accommodation Boys", value: "Accommodation Boys" },
  { Label: "Accommodation Girls", value: "Accommodation Girls" },
  { Label: "Hall Arrangement", value: "Hall Arrangement" },
  { Label: "Volunteers Captain", value: "Volunteers Captain" },
  { Label: "Group Leaders", value: "Group Leaders" },
  { Label: "Local Arrangements", value: "Local Arrangements" },
  { Label: "Medical", value: "Medical" },
  { Label: "Music", value: "Music" },
  { Label: "Transportation", value: "Transportation" },
  { label: "No", value: "No" },
];

export const zone = [
  { label: "ALAPPUZHA", value: "ALAPPUZHA" },
  { label: "ANGAMALY", value: "ANGAMALY" },
  { label: "CHANGANASSERRY", value: "CHANGANASSERRY" },
  { label: "CHERTHALA", value: "CHERTHALA" },
  { label: "ERNAKULAM", value: "ERNAKULAM" },
  { label: "IDUKKI", value: "IDUKKI" },
  { label: "IRINJALAKKUDA", value: "IRINJALAKKUDA" },
  { label: "KANJIRAPPALLY", value: "KANJIRAPPALLY" },
  { label: "KANNUR", value: "KANNUR" },
  { label: "KASARGOD", value: "KASARGOD" },
  { label: "KATTAPPANA", value: "KATTAPPANA" },
  { label: "KOLLAM", value: "KOLLAM" },
  { label: "KOTHAMANGALAM", value: "KOTHAMANGALAM" },
  { label: "KOTTAYAM", value: "KOTTAYAM" },
  { label: "KOZHIKODE", value: "KOZHIKODE" },
  { label: "MANANTHAVADY", value: "MANANTHAVADY" },
  { label: "NEYYATTINKARA", value: "NEYYATTINKARA" },
  { label: "PALA", value: "PALA" },
  { label: "PALAKKAD", value: "PALAKKAD" },
  { label: "PUNALUR", value: "PUNALUR" },
  { label: "THALASSERY", value: "THALASSERY" },
  { label: "THRISSUR", value: "THRISSUR" },
  { label: "TRIVANDRUM", value: "TRIVANDRUM" },
] as const;
