export const year = [
  { label: "1st", value: "1st" },
  { label: "2nd", value: "2nd" },
  { label: "3rd", value: "3rd" },
  { label: "4th", value: "4th" },
  { label: "5th", value: "5th" },
  { label: "Pass-out", value: "passout" },
] as const;

export const zone = [
  { label: "ALAPPUZHA", value: "ALAPPUZHA" },
  { label: "ANGAMALY", value: "ANGAMALY" },
  { label: "CHANGANASSERRY", value: "CHANGANASSERRY" },
  { label: "CHERTHALA", value: "CHERTHALA" },
  { label: "ERNAKULAM", value: "ERNAKULAM" },
  { label: "IDUKKI", value: "IDUKKI" },
  { label: "IRINJALAKKUDA", value: "IRINJALAKKUDA" },
  { label: "KANJIRAPPALLY", value: "KANJIRAPPALLY" },
  { label: "KANNUR", value: "KANNUR" },
  { label: "KASARGOD", value: "KASARGOD" },
  { label: "KATTAPPANA", value: "KATTAPPANA" },
  { label: "KOLLAM", value: "KOLLAM" },
  { label: "KOTHAMANGALAM", value: "KOTHAMANGALAM" },
  { label: "KOTTAYAM", value: "KOTTAYAM" },
  { label: "KOZHIKODE", value: "KOZHIKODE" },
  { label: "MANANTHAVADY", value: "MANANTHAVADY" },
  { label: "NEYYATTINKARA", value: "NEYYATTINKARA" },
  { label: "PALA", value: "PALA" },
  { label: "PALAKKAD", value: "PALAKKAD" },
  { label: "PUNALUR", value: "PUNALUR" },
  { label: "THALASSERY", value: "THALASSERY" },
  { label: "THRISSUR", value: "THRISSUR" },
  { label: "TRIVANDRUM", value: "TRIVANDRUM" },
] as const;
